### PR TITLE
Fix unescaped closing bracket

### LINKED ISSUE #36: Unescaped closing bracket ending RegularExpressionLiteral early
JS-tokens ends the RegularExpressionLiteral when it reaches a `]`, but Firefox and Chrome treat it as if it has been escaped.

```js
> [...jsTokens("/xyz]def/")]
[
  { type: 'RegularExpressionLiteral', value: '/xyz', closed: false },
  { type: 'Punctuator', value: ']' },
  { type: 'IdentifierName', value: 'def' },
  { type: 'Punctuator', value: '/' }
]
> /xyz]def/
/xyz]def/
> [...jsTokens("/xyz]def*/")]
[
  { type: 'RegularExpressionLiteral', value: '/xyz', closed: false },
  { type: 'Punctuator', value: ']' },
  { type: 'IdentifierName', value: 'def' },
  { type: 'Punctuator', value: '*' },
  { type: 'RegularExpressionLiteral', value: '/', closed: false }
]
> /xyz]def*/
/xyz]def*/
```

Encountered in a real file in [fluent.js](https://github.com/projectfluent/fluent.js/blob/e99614eb7fdc0ac6d09ee2cadf8bc05763c51ac1/fluent-bundle/src/resource.ts#L59).

I'm not sure if this is technically a bug with JS-tokens. The regex does not match [the spec](https://tc39.es/ecma262/#sec-literals-regular-expression-literals), so this means Chrome and Firefox go against the spec. However, they will likely not fix this due to backwards compatibility, so it seems more appropriate to update JS-tokens.

### PR DESCRIPTION
**Pull request by jared-hughes**
Fixes #36

### CODE REVIEW

File: index.coffee [hunk 1]
```diff
@@ -21,6 +21,8 @@ RegularExpressionLiteral = ///
     (?![ / \] \\ ]).
```
Comment (lydell) [inline index.coffee:21]: Would it make more sense to remove `\]` from here instead?

Comment (jared-hughes) [reply index.coffee]: Right, fixed.
